[package]
name = "wasm-sample"
version = "0.1.0"
edition = "2021"


[dependencies]
wasm-bindgen = "0.2.63"
wee_alloc = "0.4.5"
interpolator = { path = "../interpolator" }


[lib]
crate-type = ["cdylib"]
