name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: apps/yield_curve_wasm
        run: cargo build --verbose
      - name: Run tests
        working-directory: apps/yield_curve_wasm
        run: cargo test --verbose

  # create cargo document.
  doc:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Run doc
        working-directory: apps/yield_curve_wasm
        run: cargo doc --no-deps

      - name: Deploy
        uses: actions/upload-pages-artifact@v1
        with:
          path: apps/yield_curve_wasm/target/doc

  deploy:
    needs: doc
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          branch: gh-pages
          folder: apps/yield_curve_wasm/target/doc
